# Generated by Django 5.1.1 on 2024-12-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_alter_post_title_alter_post_user_and_more'),
        ('theme', '0006_alter_post_title_alter_profile_avatar'),
    ]

    operations = [
    ]
