# Generated by Django 5.1.1 on 2024-11-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_merge_20241127_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardprogress',
            name='correctCount',
            field=models.IntegerField(default=0),
        ),
    ]
