# Generated by Django 5.1.1 on 2024-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_usercardprogress_studied_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
