# Generated by Django 5.1.1 on 2024-12-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0010_profile_last_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardprogress',
            name='last_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
