# Generated by Django 5.1.3 on 2024-12-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_merge_20241127_1241'),
        ('theme', '0011_usercardprogress_last_reset'),
    ]

    operations = [
    ]
