# Generated by Django 5.1.1 on 2024-12-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0012_merge_20241203_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardprogress',
            name='incorrectCount',
            field=models.IntegerField(default=0),
        ),
    ]
